homework69/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]

webapp/urls.py
from django.urls import path

from webapp.views import index_view, get_token_view, math_action

app_name = 'webapp'

urlpatterns = [
    path('', index_view),
    path('get_token/', get_token_view, name='get_token_view'),
    path('add/', math_action, name='add'),
    path('subtract/', math_action, name='subtract'),
    path('multiply/', math_action, name='multiply'),
    path('divide/', math_action, name='divide'),
]

webapp/models.py
from django.db import models

# Create your models here.

webapp/views.py
import json

from django.http import JsonResponse, HttpResponseNotAllowed, HttpResponse
# Create your views here.
from django.shortcuts import render
from django.views.decorators.csrf import ensure_csrf_cookie


def index_view(request):
    return render(request, 'index.html')


@ensure_csrf_cookie
def get_token_view(request, *args, **kwargs):
    if request.method == 'GET':
        return HttpResponse()
    return HttpResponseNotAllowed('Only GET request are allowed')


def math_action(request):
    body = json.loads(request.body)
    action = request.META.get('PATH_INFO').strip('/')
    a = str(body.get('a'))
    b = str(body.get('b'))
    if not a.isdigit():
        response = JsonResponse({'error': f'{a}  not integer'})
        response.status_code = 400
        return response
    if not b.isdigit():
        response = JsonResponse({'error': f'{b} not integer'})
        response.status_code = 400
        return response
    if action == 'add':
        c = int(a) + int(b)
        answer = {'answer': c}
        return JsonResponse(answer)
    if action == 'subtract':
        c = int(a) - int(b)
        answer = {'answer': c}
        return JsonResponse(answer)
    if action == 'multiply':
        c = int(a) * int(b)
        answer = {'answer': c}
        return JsonResponse(answer)
    if action == 'divide':
        if int(b) == 0:
            response = JsonResponse({'error': 'zero division error'})
            response.status_code = 400
            return response
        else:
            c = int(a) / int(b)
            answer = {'answer': c}
            return JsonResponse(answer)

webapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>homework69</title>
</head>
<body>
<h1 style="text-align: center">Math actions</h1>
<br>
<div style="text-align: center">
    <input id="firstnum" type="text" placeholder="Enter first number">
    <br>
    <br>
    <input id="secondnum" type="text" placeholder="Enter second number">
</div>
<br>
<div style="text-align: center">
    <button><a href="{% url 'webapp:add' %}" id="add" class="btn"
               data-action="add">add</a></button>
    <br>
    <button><a href="{% url 'webapp:subtract' %}" id="subtract" class="btn"
               data-action="subtract">subtract</a></button>
    <br>
    <button><a href="{% url 'webapp:multiply' %}" id="multiply" class="btn"
               data-action="multiply">multiply</a></button>
    <br>
    <button><a href="{% url 'webapp:divide' %}" id="divide" class="btn"
               data-action="divide">divide</a></button>
    <br>
</div>
<br>
<div style="text-align: center"><h3>Result:</h3>
    <p style="text-align: center" id="result">Answer</p>
</div>

<script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    const csrftoken = getCookie('csrftoken');

    async function getResult(event) {
        event.preventDefault()
        let url = await event.target.href
        let firstnum = document.getElementById('firstnum')
        let secondnum = document.getElementById('secondnum')
        let a = firstnum.value
        let b = secondnum.value
        console.log(a, b)
        let body = {
            "a": a,
            "b": b
        }
        let response = await makeRequest(url, body)

        let p = document.getElementById('result')
        p.style = 'color:green'
        p.innerText = response.answer
    }

    let btnList = document.getElementsByClassName('btn')
    for (let i = 0; i < btnList.length; i++)
        btnList[i].addEventListener('click', () => getResult(event))

    async function makeRequest(url, body) {
        let response = await fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json;charset=utf-8',
                'X-CSRFToken': csrftoken
            },
            body: JSON.stringify(body),
            mode: 'same-origin'
        });

        if (response.ok) {
            return await response.json();
        } else {
            let p = document.getElementById('result')
            p.style = 'color:red'
            let error = await response.json()
            p.innerText = error.error
            console.log(await response.json())
        }
    }
</script>

</body>
</html>